### ISSUE TITLE
Jefferson County new cases reporting

### ISSUE THREAD

**Issue by lgfelton** [slu-openGIS/covid_daily_viz#1]
Other than one day where new cases were reported (sept 17, I think), no new cases have been reported for Jefferson County zip codes. Is there something wrong in the Jefferson County data source?

**Comment by chris-prener** [comment]
It hasn't been updated. Some jurisdictions have moved to either end ZIP code reporting altogether or to one per week (the City of St. Louis, for example).

**Comment by lgfelton** [comment]
Thank you!LarrySent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Christopher Prener ***@***.***> Date: 9/25/21  7:18 PM  (GMT-06:00) To: slu-openGIS/covid_daily_viz ***@***.***> Cc: lgfelton ***@***.***>, Author ***@***.***> Subject: Re: [slu-openGIS/covid_daily_viz] Jefferson County new cases reporting (#1) 
It hasn't been updated. Some jurisdictions have moved to either end ZIP code reporting altogether or to one per week (the City of St. Louis, for example).
