### ISSUE TITLE
Why are ther no New cases reported in st. Louis county 11/11

### ISSUE THREAD

**Issue by lgfelton** [slu-openGIS/covid_daily_viz#2]

**Comment by chris-prener** [comment]
Almost certainly Veteran's Day meant that they were not working, and thus the dashboard was not updated.

**Comment by lgfelton** [comment]
Chris,
My apologies. I should have realized that.
Sorry to have bothered you with this.
Larry
    On Friday, November 12, 2021, 09:22:10 AM CST, Christopher Prener ***@***.***> wrote:  
 
 


Almost certainly Veteran's Day meant that they were not working, and thus the dashboard was not updated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chris-prener** [comment]
No worries - two things to keep in mind - this is going to become more frequent over the holidays, and public health departments are starting to re-evaluate whether resources spent on this type of reporting are the best use of their time.
